"""add_topic_language

Revision ID: 1006a444a0e2
Revises: eb3b04086c4b
Create Date: 2025-12-16 21:17:17.552466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1006a444a0e2'
down_revision: Union[str, Sequence[str], None] = 'eb3b04086c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add as nullable
    op.add_column('topics', sa.Column('language', sa.String(), server_default='english', nullable=False))
    # Note: server_default allows NOT NULL in sqlite if adding column
    # The previous error was because I didn't have server_default in the migration file, only in model. 
    # Alembic autogen sometimes misses server_default if it's a python side default?
    # Actually, let's just use server_default='english'
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'language')
    # ### end Alembic commands ###
