"""add session_id and create access_codes

Revision ID: 35c3572223d5
Revises: 4f1ca304ce5c
Create Date: 2025-12-16 00:44:23.217216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c3572223d5'
down_revision: Union[str, Sequence[str], None] = '4f1ca304ce5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_codes_code'), 'access_codes', ['code'], unique=True)
    op.create_index(op.f('ix_access_codes_id'), 'access_codes', ['id'], unique=False)
    op.add_column('interaction_logs', sa.Column('session_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_interaction_logs_session_id'), 'interaction_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_logs_session_id'), table_name='interaction_logs')
    op.drop_column('interaction_logs', 'session_id')
    op.drop_index(op.f('ix_access_codes_id'), table_name='access_codes')
    op.drop_index(op.f('ix_access_codes_code'), table_name='access_codes')
    op.drop_table('access_codes')
    # ### end Alembic commands ###
