"""add_description_to_topic

Revision ID: 8c20ffaf6b1e
Revises: 4cfffed5dc5f
Create Date: 2025-12-16 18:38:27.424173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c20ffaf6b1e'
down_revision: Union[str, Sequence[str], None] = '4cfffed5dc5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'description')
    # ### end Alembic commands ###
